# Generated by Django 2.2.2 on 2019-06-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '不明')], default='male', max_length=10)),
                ('email', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
