# Generated by Django 2.2.2 on 2019-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='message_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='wait_time',
            field=models.IntegerField(default=0),
        ),
    ]
