# Generated by Django 2.2.2 on 2019-06-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190630_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='message_id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='wait_time',
            field=models.CharField(max_length=10),
        ),
    ]
