# Generated by Django 2.2.2 on 2019-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='company',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='selfpro',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
